### ISSUE TITLE
LISTEN.moe app crashes when in background with phone locked

### ISSUE THREAD

**Issue by 9stella** [LISTEN-moe/android-app#94]
**Please describe the problem you are having in as much detail as possible:**
The app crashes when I minimize it and lock my phone.
**Further details:**
- Logcat:
`[ 05-23 14:29:39.367  1664:11047 W/ActivityManager ]
Foreground service started from background can not have location/camera/microphone access: service me.echeung.moemoekyun/.service.AppService

[ 05-23 14:29:39.368  1664:11047 W/ActivityManager ]
Background started FGS: Disallowed [callingPackage: me.echeung.moemoekyun; callingUid: 10274; uidState: CAC ; uidBFSL: n/a; intent: Intent { cmp=me.echeung.moemoekyun/.service.AppService }; code:DENIED; tempAllowListReason:<null>; targetSdkVersion:34; callerTargetSdkVersion:34; startForegroundCount:1; bindFromPackage:null: isBindService:false]

[ 05-23 14:29:39.368  1664:11047 W/ActivityManager ]
Service.startForeground() not allowed due to mAllowStartForeground false: service me.echeung.moemoekyun/.service.AppService

[ 05-23 14:29:39.395 29792:29857 W/AudioTrack ]
getTimestamp_l(1114): retrograde timestamp time corrected, 97913323297542 < 97913691573427

[ 05-23 14:29:39.404 29792:29828 E/AndroidRuntime ]
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: me.echeung.moemoekyun, PID: 29792
android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service me.echeung.moemoekyun/.service.AppService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5015)
	at android.os.Parcel.readParcelable(Parcel.java:4997)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3177)
	at android.os.Parcel.createException(Parcel.java:3166)
	at android.os.Parcel.readException(Parcel.java:3149)
	at android.os.Parcel.readException(Parcel.java:3091)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6861)
	at android.app.Service.startForeground(Service.java:775)
	at me.echeung.moemoekyun.service.MusicNotifier.update(Unknown Source:270)
	at me.echeung.moemoekyun.service.AppService.update(Unknown Source:31)
	at me.echeung.moemoekyun.service.AppService.access$update(Unknown Source:0)
	at me.echeung.moemoekyun.service.AppService$onCreate$1.invokeSuspend$update(Unknown Source:0)
	at me.echeung.moemoekyun.service.AppService$onCreate$1.access$invokeSuspend$update(Unknown Source:0)
	at me.echeung.moemoekyun.service.AppService$onCreate$1$2.invoke(SourceFile:0)
	at me.echeung.moemoekyun.service.AppService$onCreate$1$2.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Unknown Source:50)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Unknown Source:38)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(SourceFile:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Unknown Source:20)
	at kotlinx.coroutines.CoroutineStart.invoke(Unknown Source:27)
	at kotlinx.coroutines.AbstractCoroutine.start(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Unknown Source:22)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Unknown Source:12)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Unknown Source:112)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$2$2.invokeSuspend(Unknown Source:83)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$2$2.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$2$2.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Unknown Source:295)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dde82d9, Dispatchers.IO]

[ 05-23 14:29:39.413  1664:11047 W/ActivityTaskManager ]
  Force finishing activity me.echeung.moemoekyun/.ui.MainActivity

[ 05-23 14:29:39.435  1664:11047 W/UserManagerService ]
Requested status bar icon for non-badged user 0

[ 05-23 14:29:39.534  1335: 7463 E/mediaserver ]
unlinkToDeath: removed reference to death recipient but unlink failed: DEAD_OBJECT

[ 05-23 14:29:39.535  1335: 7463 E/IPCThreadState ]
attemptIncStrongHandle(18): Not supported

[ 05-23 14:29:39.535 25359:25359 W/AudioMediaPlayerWrapper ]
The session was destroyed me.echeung.moemoekyun

[ 05-23 14:29:39.536  1664: 3454 W/InputManager-JNI ]
Input channel object 'f87c1af me.echeung.moemoekyun/me.echeung.moemoekyun.ui.MainActivity (client)' was disposed without first being removed with the input manager!

[ 05-23 14:29:39.539 25359:25386 W/bt_stack ]
[WARNING:device.cc(1720)] Device is not registered for now playing updates

[ 05-23 14:29:39.539 25359:25386 W/bt_stack ]
[WARNING:device.cc(1817)] Device is not registered for play position updates

[ 05-23 14:29:39.539 25359:25386 W/bt_stack ]
[WARNING:device.cc(1695)] Device is not registered for track changed updates

[ 05-23 14:29:39.553  1664: 1800 W/ActivityManager ]
setHasOverlayUi called on unknown pid: 29792

[ 05-23 14:29:39.554  1664: 1823 W/UsageStatsService ]
Unexpected activity event reported! (me.echeung.moemoekyun/me.echeung.moemoekyun.ui.MainActivity event : 23 instanceId : 107453097)`
- App version: 6.0.2
- Android version: Upside Down Cake (14)
- Device: Samsung Galaxy S20 FE 4G (r8q) (LineageOS 21 official)
- Priority this should have – please be realistic and elaborate if possible: medium

**Comment by arkon** [comment]
Are you trying to play and then immediately backgrounding the app?

**Comment by 9stella** [comment]
> Are you trying to play and then immediately backgrounding the app?

I always wait for the song to start playing, or it doesn't start at all and the play button does nothing.

**Comment by arkon** [comment]
Does it still crash with v6.1.0?
